### ISSUE TITLE
[Fix] 재생/멈춤 토글 추가, UserDefault 로직 추가해서 selectedTeam 안받아와지는 문제 해결

### ISSUE THREAD

**Issue by yeniful** [Gwamegis/Halmap#53]
### Task
- [x] 재생 뷰에서 재생 버튼 누르면 다시 재생되는 이슈 (→ 멈춤으로 바꾸기)
- [x] 기존 연결 해제 후 목업데이터 연결
- [x] SongInformationView UI 깨지는 것 수정
- [x] changedTeam을 selectedTeam으로 업데이트가 잘 안되는 문제 수정 → 유저 디폴트 연결
