### ISSUE TITLE
[Chore] Portrait 모드 고정, LightMode 고정, 팀 선택 ToolBar Item 위치 변경

### ISSUE THREAD

**Issue by yeniful** [Gwamegis/Halmap#55]
### Task
- [x] Portrait 모드 고정 추가하기
- [x] Light Mode 고정
- [x] ToolBar Item 위치 변경
